name: node

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.cjs'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/node.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.cjs'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Check for changes
        run: |
          git add .
          git diff --staged --exit-code

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Upload test coverage
        uses: codecov/codecov-action@v5.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
